### ISSUE TITLE
Any advantage to using this for file change detection over fsnotify?

### ISSUE THREAD

**Issue by nkev** [MichaelTJones/since#1]
Thanks for sharing this cool code, I have learned a lot. Compared to [fsnotify](https://github.com/go-fsnotify/fsnotify), I like the fact that with your `walk` library you have full control over every step of the way and don't have to rely on the OS, even though your `since` code has to poll regularly. 

So my questions are:

Is there any advantage to using this over [fsnotify](https://github.com/go-fsnotify/fsnotify) for file change detection by polling say 100-2000 files every 500ms? 

How would you compare server resource usage against fsnotify vs regular 500ms polling of 2000 files?

Which would be more robust across platforms?

**Comment by MichaelTJones** [comment]
Fsnotify is better if it works for you because the OS knows when it is
making a filesystem change and can notify any registered caller, or at
least keep a log file of recently changed files.

This should be faster.

Michael

**Comment by nkev** [comment]
Thanks Michael, I figured as much but wanted to confirm with you. Thank you for replying.
